In [26]:
import myfuncs as mf, pandas as pd, numpy as np, copy as c, spacy, glob

from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [2]:
from myfuncs import my_tokenizer, deduplicate

In [3]:
paths = glob.glob("data/*_fulltext.csv")
lst = []
for x in paths:
    df = pd.read_csv(x, index_col=0)
    lst +=  [df]
    
df = pd.concat(lst).reset_index(drop = True)
df["tokens"] = df["fulltext"].apply(my_tokenizer)

In [4]:
docs = df.set_index("fulltext_id").loc[:, "tokens"].to_dict()

In [13]:
df["fulltext"].values[1]

'Verdal kommune Innbyggertall 14.162 * Flateareal 1.547 km²\nVerran kommune Innbyggertall 2.937 * Flateareal 601 km²\nDette er utskriftsversjon av https://www.landbruksforum.no/innherred/info/index.php?viskommune=inder%C3%83%C2%83%C3%82%C2%83%C3%83%C2%82%C3%82%C2%83%C3%83%C2%83%C3%82%C2%82%C3%83%C2%82%C3%82%C2%B8y&vis_o_id=5&vis=innherredlandbruksforum&lang=bok&tema_id=4&spm_id=17'

In [9]:
vectorizer = CountVectorizer()

In [22]:
X = vectorizer.fit_transform(df["fulltext"])

In [15]:
analyze = vectorizer.build_analyzer()

In [28]:
tfidf_vector = TfidfVectorizer(tokenizer = my_tokenizer)

In [29]:
from sklearn.model_selection import train_test_split

In [31]:
X = df['fulltext'] # the features we want to analyze
ylabels = df.index # the labels, or answers, we want to test against

X_train, X_test, y_train, y_test = train_test_split(X, ylabels, test_size=0.3)

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
base_document = df.fulltext[0]
documents = [df.fulltext[1]]

#def process_tfidf_similarity():
vectorizer = TfidfVectorizer()

# To make uniformed vectors, both documents need to be combined first.
documents.insert(0, base_document)
embeddings = vectorizer.fit_transform(documents)

cosine_similarities = cosine_similarity(embeddings[0:1], embeddings[1:]).flatten()

cosine_similarities

array([0.01425542])

In [59]:
cosine_similarities

array([0.01425542])

In [58]:
embeddings[0:1], embeddings[1:]

(<1x302 sparse matrix of type '<class 'numpy.float64'>'
 	with 267 stored elements in Compressed Sparse Row format>,
 <1x302 sparse matrix of type '<class 'numpy.float64'>'
 	with 38 stored elements in Compressed Sparse Row format>)

In [41]:
cosine_similarities

array([[0.01425542]])

In [47]:
list(docs.values())

['nynorsk',
 'opplæringa',
 '2',
 'primært',
 'retta',
 'lærarar',
 'underviser',
 'grunnopplæringa',
 'nyttig',
 'heve',
 'nynorskkompetansen',
 'emnet',
 'eit',
 'praktisk',
 'undervisningsorientert',
 'perspektiv',
 'auka',
 'kompetanse',
 'nynorsk',
 'undervise',
 'målet',
 'studiet',
 'studentane',
 'drive',
 'opplæring',
 'nynorsk',
 'nivå',
 'grunnopplæringa',
 'tråd',
 'intensjonane',
 'læreplanen',
 'studentane',
 'utvikle',
 'eigenkompetanse',
 'nynorsk',
 'vurdere',
 'vidareutvikle',
 'eigen',
 'undervisningspraksis',
 'nynorsk',
 'høve',
 'læreplanen',
 'kjenne',
 'bruke',
 'relevant',
 'fagleg',
 'fagdidaktisk',
 'teori',
 'nynorsk',
 'opplæringa',
 '2',
 'no122',
 'eit',
 'kultur',
 'danningsperspektiv',
 'det',
 'didaktiske',
 'perspektivet',
 'gjennomgåande',
 'studiet',
 'læringsutbytte',
 'i',
 'samsvar',
 'nasjonale',
 'kvalifikasjonsrammeverket',
 'studenten',
 'følgjande',
 'læringsutbytte',
 'fullført',
 'emne',
 'ved',
 'fullføring',
 'emnet',
 'studenten',
 'kun

In [68]:
vectorizer2 = TfidfVectorizer()

In [97]:
df.fulltext

0      Nynorsk i opplæringa 2 er primært retta mot læ...
1      Verdal kommune Innbyggertall 14.162 * Flateare...
2      Artikler > 2017 > Elleve raketter skal avsløre...
3      Studieplan - Bachelor - barnehagelærarutdannin...
4      Skin burns\nProject owner\nProject categories\...
                             ...                        
195    Bruksformål: Mot spinnmidd på plantekulturer i...
196    Detailed Course Information - TIK4011(Science ...
197    SSA-K Endringslogg 2015-2018\nDette er Difis e...
198    Procedure for request for grounds and appeal o...
199    Emnebok  ERN 2110\nVåren 2005\nKosthold, samfu...
Name: fulltext, Length: 200, dtype: object

In [100]:
embeddings = vectorizer2.fit_transform(df.fulltext)

In [ ]:
embeddings.toarray()

In [105]:
embeddings.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.0081808 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.03246225, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00625851, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [104]:
pd.Series(embeddings.toarray())

ValueError: Data must be 1-dimensional

In [75]:
from tqdm import tqdm

In [90]:
dct = dict()
x_count = 0
for x in tqdm(embeddings):
    y_count = 0
    for y in embeddings:
        cosine_similarities = cosine_similarity(embeddings[x_count], embeddings[y_count]).flatten()
        if x_count in dct.keys():
            dct[x_count].update({y_count : cosine_similarities[0]})
        elif x_count not in dct.keys():
            dct[x_count] = {y_count : cosine_similarities[0]}
        
        
        y_count += 1
        
    x_count += 1
        

200it [00:32,  6.09it/s]


In [91]:
cdf = pd.DataFrame(dct)
cdf.columns = df.fulltext_id
cdf.index = df.fulltext_id

In [ ]:
cosine_similarities

In [93]:
cdf.to_csv("data/tf_idf.csv")

In [50]:
embeddings[:1]

<1x56952 sparse matrix of type '<class 'numpy.float64'>'
	with 267 stored elements in Compressed Sparse Row format>

In [66]:
embeddings[1]

<1x56952 sparse matrix of type '<class 'numpy.float64'>'
	with 38 stored elements in Compressed Sparse Row format>

In [62]:
cosine_similarities = cosine_similarity(embeddings[0], embeddings[1]).flatten()

In [56]:
embeddings[1]

<1x56952 sparse matrix of type '<class 'numpy.float64'>'
	with 38 stored elements in Compressed Sparse Row format>

In [63]:
cosine_similarities

array([0.0052601])

In [65]:
embeddings.shape

(200, 56952)